services:
  php-fpm:
    build: 
      context: ./
      dockerfile: docker/php.Dockerfile
    volumes:
      - './:/var/www/html'
    working_dir: '/var/www/html'
    networks:
      - dev-network
    extra_hosts:
      - host.docker.internal:host-gateway
  web:
    image: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'
    networks:
      - dev-network
networks:
  dev-network:
    # driver: bridge